// Mocks generated by Mockito 5.4.6 from annotations
// in projek_uts_mbr/test/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:projek_uts_mbr/databases/database.dart' as _i3;
import 'package:projek_uts_mbr/databases/vendorDatabase.dart' as _i5;
import 'package:projek_uts_mbr/model/VendorModel.dart' as _i7;
import 'package:projek_uts_mbr/provider/language_provider.dart' as _i10;
import 'package:projek_uts_mbr/services/dataServices.dart' as _i2;
import 'package:projek_uts_mbr/services/sessionManager.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataservices_0 extends _i1.SmartFake implements _i2.Dataservices {
  _FakeDataservices_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaserService_1 extends _i1.SmartFake
    implements _i3.DatabaserService {
  _FakeDatabaserService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_2 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Vendordatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVendordatabase extends _i1.Mock implements _i5.Vendordatabase {
  MockVendordatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dataservices get dataservices =>
      (super.noSuchMethod(
            Invocation.getter(#dataservices),
            returnValue: _FakeDataservices_0(
              this,
              Invocation.getter(#dataservices),
            ),
          )
          as _i2.Dataservices);

  @override
  _i3.DatabaserService get databaserService =>
      (super.noSuchMethod(
            Invocation.getter(#databaserService),
            returnValue: _FakeDatabaserService_1(
              this,
              Invocation.getter(#databaserService),
            ),
          )
          as _i3.DatabaserService);

  @override
  set dataservices(_i2.Dataservices? value) => super.noSuchMethod(
    Invocation.setter(#dataservices, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaserService(_i3.DatabaserService? value) => super.noSuchMethod(
    Invocation.setter(#databaserService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> initDataAwal() =>
      (super.noSuchMethod(
            Invocation.method(#initDataAwal, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.Vendormodel>> getData({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i7.Vendormodel>>.value(
              <_i7.Vendormodel>[],
            ),
          )
          as _i6.Future<List<_i7.Vendormodel>>);

  @override
  _i6.Future<void> deletePackage(String? vendorEmail, String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#deletePackage, [vendorEmail, packageName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePackage(
    String? vendorEmail,
    String? oldPackageName,
    String? newPackageName,
    Map<String, dynamic>? newPackageData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePackage, [
              vendorEmail,
              oldPackageName,
              newPackageName,
              newPackageData,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.Vendormodel?> getVendorByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getVendorByEmail, [email]),
            returnValue: _i6.Future<_i7.Vendormodel?>.value(),
          )
          as _i6.Future<_i7.Vendormodel?>);

  @override
  _i6.Future<_i7.Vendormodel?> getVendorByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getVendorByName, [name]),
            returnValue: _i6.Future<_i7.Vendormodel?>.value(),
          )
          as _i6.Future<_i7.Vendormodel?>);

  @override
  _i6.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<int> insertVendor(dynamic vendor, {String? kategori = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#insertVendor, [vendor], {#kategori: kategori}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i7.Penyedia?> LoginVendor(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#LoginVendor, [email, password]),
            returnValue: _i6.Future<_i7.Penyedia?>.value(),
          )
          as _i6.Future<_i7.Penyedia?>);

  @override
  _i6.Future<void> printAllVendors() =>
      (super.noSuchMethod(
            Invocation.method(#printAllVendors, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePasswords() =>
      (super.noSuchMethod(
            Invocation.method(#updatePasswords, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.Penyedia>> searchVendors(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchVendors, [query]),
            returnValue: _i6.Future<List<_i7.Penyedia>>.value(<_i7.Penyedia>[]),
          )
          as _i6.Future<List<_i7.Penyedia>>);

  @override
  _i6.Future<void> updateVendorImage(String? email, String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateVendorImage, [email, imageUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i8.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get IS_LOGGED_IN =>
      (super.noSuchMethod(
            Invocation.getter(#IS_LOGGED_IN),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#IS_LOGGED_IN),
            ),
          )
          as String);

  @override
  String get EMAIL =>
      (super.noSuchMethod(
            Invocation.getter(#EMAIL),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#EMAIL),
            ),
          )
          as String);

  @override
  String get userType =>
      (super.noSuchMethod(
            Invocation.getter(#userType),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#userType),
            ),
          )
          as String);

  @override
  String get notif_status =>
      (super.noSuchMethod(
            Invocation.getter(#notif_status),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#notif_status),
            ),
          )
          as String);

  @override
  _i6.Future<void> createLoginSession(String? email, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#createLoginSession, [email, type]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> getUserType() =>
      (super.noSuchMethod(
            Invocation.method(#getUserType, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> setNotificationEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationEnabled, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> getNotificationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationStatus, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [LanguageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageProvider extends _i1.Mock implements _i10.LanguageProvider {
  MockLanguageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_2(this, Invocation.getter(#locale)),
          )
          as _i4.Locale);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadLocale() =>
      (super.noSuchMethod(
            Invocation.method(#loadLocale, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setLocale(_i4.Locale? newLocale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [newLocale]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String getLanguageName() =>
      (super.noSuchMethod(
            Invocation.method(#getLanguageName, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getLanguageName, []),
            ),
          )
          as String);

  @override
  _i4.Locale getLocaleFromName(String? languageName) =>
      (super.noSuchMethod(
            Invocation.method(#getLocaleFromName, [languageName]),
            returnValue: _FakeLocale_2(
              this,
              Invocation.method(#getLocaleFromName, [languageName]),
            ),
          )
          as _i4.Locale);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
