// Mocks generated by Mockito 5.4.6 from annotations
// in projek_uts_mbr/test/loginVendor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:projek_uts_mbr/databases/database.dart' as _i3;
import 'package:projek_uts_mbr/databases/vendorDatabase.dart' as _i4;
import 'package:projek_uts_mbr/model/VendorModel.dart' as _i6;
import 'package:projek_uts_mbr/services/dataServices.dart' as _i2;
import 'package:projek_uts_mbr/services/sessionManager.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataservices_0 extends _i1.SmartFake implements _i2.Dataservices {
  _FakeDataservices_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaserService_1 extends _i1.SmartFake
    implements _i3.DatabaserService {
  _FakeDatabaserService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Vendordatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVendordatabase extends _i1.Mock implements _i4.Vendordatabase {
  @override
  _i2.Dataservices get dataservices =>
      (super.noSuchMethod(
            Invocation.getter(#dataservices),
            returnValue: _FakeDataservices_0(
              this,
              Invocation.getter(#dataservices),
            ),
            returnValueForMissingStub: _FakeDataservices_0(
              this,
              Invocation.getter(#dataservices),
            ),
          )
          as _i2.Dataservices);

  @override
  _i3.DatabaserService get databaserService =>
      (super.noSuchMethod(
            Invocation.getter(#databaserService),
            returnValue: _FakeDatabaserService_1(
              this,
              Invocation.getter(#databaserService),
            ),
            returnValueForMissingStub: _FakeDatabaserService_1(
              this,
              Invocation.getter(#databaserService),
            ),
          )
          as _i3.DatabaserService);

  @override
  set dataservices(_i2.Dataservices? value) => super.noSuchMethod(
    Invocation.setter(#dataservices, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaserService(_i3.DatabaserService? value) => super.noSuchMethod(
    Invocation.setter(#databaserService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initDataAwal() =>
      (super.noSuchMethod(
            Invocation.method(#initDataAwal, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Vendormodel>> getData({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i6.Vendormodel>>.value(
              <_i6.Vendormodel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i6.Vendormodel>>.value(
              <_i6.Vendormodel>[],
            ),
          )
          as _i5.Future<List<_i6.Vendormodel>>);

  @override
  _i5.Future<void> deletePackage(String? vendorEmail, String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#deletePackage, [vendorEmail, packageName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePackage(
    String? vendorEmail,
    String? oldPackageName,
    String? newPackageName,
    Map<String, dynamic>? newPackageData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePackage, [
              vendorEmail,
              oldPackageName,
              newPackageName,
              newPackageData,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.Vendormodel?> getVendorByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getVendorByEmail, [email]),
            returnValue: _i5.Future<_i6.Vendormodel?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Vendormodel?>.value(),
          )
          as _i5.Future<_i6.Vendormodel?>);

  @override
  _i5.Future<_i6.Vendormodel?> getVendorByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getVendorByName, [name]),
            returnValue: _i5.Future<_i6.Vendormodel?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Vendormodel?>.value(),
          )
          as _i5.Future<_i6.Vendormodel?>);

  @override
  _i5.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i5.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<int> insertVendor(dynamic vendor, {String? kategori = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#insertVendor, [vendor], {#kategori: kategori}),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i6.Penyedia?> LoginVendor(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#LoginVendor, [email, password]),
            returnValue: _i5.Future<_i6.Penyedia?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Penyedia?>.value(),
          )
          as _i5.Future<_i6.Penyedia?>);

  @override
  _i5.Future<void> printAllVendors() =>
      (super.noSuchMethod(
            Invocation.method(#printAllVendors, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePasswords() =>
      (super.noSuchMethod(
            Invocation.method(#updatePasswords, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Penyedia>> searchVendors(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchVendors, [query]),
            returnValue: _i5.Future<List<_i6.Penyedia>>.value(<_i6.Penyedia>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.Penyedia>>.value(
              <_i6.Penyedia>[],
            ),
          )
          as _i5.Future<List<_i6.Penyedia>>);

  @override
  _i5.Future<void> updateVendorImage(String? email, String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateVendorImage, [email, imageUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i7.SessionManager {
  @override
  String get IS_LOGGED_IN =>
      (super.noSuchMethod(
            Invocation.getter(#IS_LOGGED_IN),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#IS_LOGGED_IN),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#IS_LOGGED_IN),
            ),
          )
          as String);

  @override
  String get EMAIL =>
      (super.noSuchMethod(
            Invocation.getter(#EMAIL),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#EMAIL),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#EMAIL),
            ),
          )
          as String);

  @override
  String get userType =>
      (super.noSuchMethod(
            Invocation.getter(#userType),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#userType),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#userType),
            ),
          )
          as String);

  @override
  String get notif_status =>
      (super.noSuchMethod(
            Invocation.getter(#notif_status),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#notif_status),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#notif_status),
            ),
          )
          as String);

  @override
  _i5.Future<void> createLoginSession(String? email, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#createLoginSession, [email, type]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> getEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getUserType() =>
      (super.noSuchMethod(
            Invocation.method(#getUserType, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setNotificationEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationEnabled, [value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> getNotificationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationStatus, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
